mongodb:
  host: localhost
  port: 27017
  username: sagargupta1610
  password: 2bo3v71KNDqEsYDC
  cluster: cluster-1
  database: BMS-DB
  connection_string: mongodb+srv://sagargupta1610:2bo3v71KNDqEsYDC@cluster-1.pxfmgiw.mongodb.net/
